sudo: True

language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get install -yqq gfortran libblas-dev liblapack-dev
  - pip install scipy  # faster
install:
  - "pip install ."
script: nosetests
