from .DataReader import DataReader

from .AmazonElectronicsReader import AmazonElectronicsReader
from .AmazonAutomotiveReader import AmazonAutomotiveReader
from .AmazonBooksReader import AmazonBooksReader
from .BookCrossingReader import BookCrossingReader
from .BrightkiteReader import BrightkiteReader
from .CiteULikeReader import CiteULike_aReader, CiteULike_tReader
from .DeliciousHetrec2011Reader import DeliciousHetrec2011Reader
from .EpinionsReader import EpinionsReader
from .LastFMHetrec2011Reader import LastFMHetrec2011Reader
from .Movielens100KReader import Movielens100KReader
from .Movielens1MReader import Movielens1MReader
from .Movielens10MReader import Movielens10MReader
from .Movielens20MReader import Movielens20MReader
from .Movielens25MReader import Movielens25MReader
from .NetflixEnhancedReader import NetflixEnhancedReader
from .NetflixPrizeReader import NetflixPrizeReader
from .SpotifyChallenge2018Reader import SpotifyChallenge2018Reader
from .SpotifySkipPredictionReader import SpotifySkipPredictionReader
from .Steam import SteamReader
from .TheMoviesDatasetReader import TheMoviesDatasetReader
from .ThirtyMusicReader import ThirtyMusicReader
from .TVAudienceReader import TVAudienceReader
from .XingChallenge2016Reader import XingChallenge2016Reader
from .XingChallenge2017Reader import XingChallenge2017Reader
from .YahooMovies import YahooMoviesReader
from .YelpReader import YelpReader
